apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: test-container
spec:
  template:
    metadata:
      name: nginx-container
      labels:
        type: test-container
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
